using System;
public enum FavoriteTags
{
    ACAO,
    AVENTURA,
    COMEDIA,
    CHANCHADA,
    COMEDIA_DE_ACAO,
    COMEDIA_DE_TERROR,
    COMEDIA_DRAMATICA,
    COMEDIA_ROMANTICA,
    DANCA,
    DOCUMENTARIO,
    DOCUFICCAO,
    DRAMA,
    ESPIONAGEM,
    FAROESTE,
    FANTASIA,
    FANTASIA_CIENTIFICA,
    FICCAO_CIENTIFICA,
    FILMES_COM_TRUQUES,
    FILMES_DE_GUERRA,
    MISTERIO_MUSICAL,
    FILME_POLICIAL,
    ROMANCE,
    TERROR,
    THRILLER,
}

public enum Awards
{
    CENARIO_INCRIVEL,
    MASTERPIECE,
    ATORES_SUPIMPAS,
    TECNICAS_DE_FILMAGEM_INCRIVEIS,
}
